<?php
require_once '../middleware/authGuard.php';

// --- GET FILTERS ---
$s = $_GET['s'] ?? '';
$f = $_GET['f'] ?? '';
$d1 = $_GET['d1'] ?? '';
$d2 = $_GET['d2'] ?? '';
$dup = isset($_GET['dup']) ? (int)$_GET['dup'] : 0; 

// --- BUILD QUERY ---
if ($dup) {
    $sql = "SELECT t1.* FROM meter_removal t1 INNER JOIN (SELECT acc_no FROM meter_removal GROUP BY acc_no HAVING COUNT(id) > 1) t2 ON t1.acc_no = t2.acc_no WHERE 1=1";
} else {
    $sql = "SELECT * FROM meter_removal WHERE 1=1";
}

if (!empty($s)) { $s_cl = $conn->real_escape_string($s); $sql .= " AND (job_no LIKE '%$s_cl%' OR acc_no LIKE '%$s_cl%' OR meter_no LIKE '%$s_cl%')"; }
if (!empty($f)) { $f_cl = $conn->real_escape_string($f); $sql .= " AND status='$f_cl'"; }
if (!empty($d1) && !empty($d2)) {
    if ($f == 'Removed') { $sql .= " AND removing_date BETWEEN '$d1' AND '$d2'"; } 
    else { $sql .= " AND created_at BETWEEN '$d1 00:00:00' AND '$d2 23:59:59'"; }
}

$sql .= " ORDER BY id DESC";
$res = $conn->query($sql);
$total_count = $res ? $res->num_rows : 0;

$status_print = empty($f) ? 'All Status' : htmlspecialchars($f);
$date_print = (!empty($d1) && !empty($d2)) ? htmlspecialchars("$d1 to $d2") : 'All Time';
$dup_print = ($dup == 1) ? 'Yes (Grouped by Account)' : 'No';
$search_print = empty($s) ? 'None' : htmlspecialchars($s);
$generated_by = isset($_SESSION['full_name']) ? htmlspecialchars($_SESSION['full_name']) : '';

// Headers for Excel
header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename=Meter_Removal_Report_' . date('Y-m-d_Hi') . '.xls');

echo "<html xmlns:x=\"urn:schemas-microsoft-com:office:excel\">";
echo "<head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'></head>";
echo "<body>";
echo "<table border='1'>";

// Title & Info
echo "<tr><th colspan='10' style='font-size:16px; text-align:center;'><b>Electricity Distribution Lanka (Pvt) Ltd</b></th></tr>";
echo "<tr><th colspan='10' style='font-size:18px; text-align:center; height: 35px;'><b>METER REMOVAL OPERATIONS REPORT</b></th></tr>";
echo "<tr><td colspan='10'></td></tr>";

echo "<tr><td colspan='2'><b>Generated By:</b></td><td colspan='8'>{$generated_by}</td></tr>";
echo "<tr><td colspan='2'><b>Date Generated:</b></td><td colspan='8'>" . date('Y-m-d H:i:s') . "</td></tr>";
echo "<tr><td colspan='2'><b>Filter Status:</b></td><td colspan='8'>{$status_print}</td></tr>";
echo "<tr><td colspan='2'><b>Date Range:</b></td><td colspan='8'>{$date_print}</td></tr>";
echo "<tr><td colspan='2'><b>Search Keyword:</b></td><td colspan='8'>{$search_print}</td></tr>";
echo "<tr><td colspan='2'><b>Unique Group View:</b></td><td colspan='8'>{$dup_print}</td></tr>";
echo "<tr><td colspan='2'><b>Total Records:</b></td><td colspan='8'>{$total_count}</td></tr>";
echo "<tr><td colspan='10'></td></tr>";

// Table Headers
echo "<tr>";
echo "<th><b>ID</b></th>";
echo "<th><b>JOB NO</b></th>";
echo "<th><b>ACCOUNT NO</b></th>";
echo "<th><b>METER NO</b></th>";
echo "<th><b>STATUS</b></th>";
echo "<th><b>CREATED DATE</b></th>";
echo "<th><b>REMOVED DATE</b></th>";
echo "<th><b>FINAL READING</b></th>";
echo "<th><b>DONE BY</b></th>";
echo "<th><b>OFFICER NOTE</b></th>";
echo "</tr>";

if ($total_count > 0) {
    while ($r = $res->fetch_assoc()) {
        $created_date = !empty($r['created_at']) ? date('Y-m-d H:i', strtotime($r['created_at'])) : '';
        $removed_date = !empty($r['removing_date']) ? $r['removing_date'] : '';
        
        echo "<tr>";
        echo "<td>" . ($r['id'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['job_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['acc_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['meter_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['status'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($created_date) . "</td>";
        echo "<td>" . htmlspecialchars($removed_date) . "</td>";
        echo "<td>" . htmlspecialchars($r['meter_reading'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['done_by'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['officer_note'] ?? '') . "</td>";
        echo "</tr>";
    }
} else {
    echo "<tr><td colspan='10' style='text-align:center;'>No records found for the selected criteria.</td></tr>";
}

// Signature area
echo "<tr><td colspan='10'></td></tr>";
echo "<tr><td colspan='10'></td></tr>";
echo "<tr><td colspan='10'></td></tr>";

echo "<tr>";
echo "<td colspan='3' style='text-align:center; border: none;'>......................................................</td>";
echo "<td colspan='4' style='border: none;'></td>";
echo "<td colspan='3' style='text-align:center; border: none;'>......................................................</td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='3' style='text-align:center; border: none;'><b>Prepared By</b></td>";
echo "<td colspan='4' style='border: none;'></td>";
echo "<td colspan='3' style='text-align:center; border: none;'><b>Approved By (Electrical Superintendent)</b></td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='3' style='text-align:center; border: none;'>{$generated_by}</td>";
echo "<td colspan='4' style='border: none;'></td>";
echo "<td colspan='3' style='text-align:center; border: none;'></td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='3' style='text-align:center; border: none;'>Date: ........................</td>";
echo "<td colspan='4' style='border: none;'></td>";
echo "<td colspan='3' style='text-align:center; border: none;'>Date: ........................</td>";
echo "</tr>";

echo "</table>";
echo "</body></html>";
exit();

