<?php
require_once '../middleware/authGuard.php';

// --- GET FILTERS ---
$s = $_GET['s'] ?? '';
$f = $_GET['f'] ?? '';
$p = $_GET['p'] ?? '';
$d1 = $_GET['d1'] ?? '';
$d2 = $_GET['d2'] ?? '';

// Build Query
$w = "WHERE 1=1";

if (!empty($s)) {
    $s_cl = $conn->real_escape_string($s);
    $w .= " AND (job_no LIKE '%$s_cl%' OR acc_no LIKE '%$s_cl%' OR old_meter_no LIKE '%$s_cl%' OR new_meter_no LIKE '%$s_cl%')";
}
if (!empty($f)) {
    $f_cl = $conn->real_escape_string($f);
    $w .= " AND status='$f_cl'";
}
if (!empty($p)) {
    $p_cl = $conn->real_escape_string($p);
    $w .= " AND phase_type='$p_cl'";
}
if (!empty($d1) && !empty($d2)) {
    // Use done_date when filtering Completed jobs, otherwise use created_at
    $date_col = ($f == 'Completed') ? 'done_date' : 'created_at';
    $w .= " AND $date_col BETWEEN '$d1' AND '$d2'";
}

$sql = "SELECT * FROM meter_change $w ORDER BY id DESC";

// Execute
$res = $conn->query($sql);
$total_count = $res ? $res->num_rows : 0;

$status_print = empty($f) ? 'All Status' : htmlspecialchars($f);
$phase_print = empty($p) ? 'All Phases' : htmlspecialchars($p);
$date_col_label = ($f == 'Completed') ? 'Completion Date' : 'Request Date';
$date_print = (!empty($d1) && !empty($d2)) ? htmlspecialchars("$d1 to $d2") . " ($date_col_label)" : 'All Time';
$search_print = empty($s) ? 'None' : htmlspecialchars($s);
$generated_by = isset($_SESSION['full_name']) ? htmlspecialchars($_SESSION['full_name']) : '';

// Headers for Excel
header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename=Meter_Change_Report_' . date('Y-m-d_Hi') . '.xls');

echo "<html xmlns:x=\"urn:schemas-microsoft-com:office:excel\">";
echo "<head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'></head>";
echo "<body>";
echo "<table border='1'>";

// Title & Info
echo "<tr><th colspan='13' style='font-size:16px; text-align:center;'><b>Electricity Distribution Lanka (Pvt) Ltd</b></th></tr>";
echo "<tr><th colspan='13' style='font-size:18px; text-align:center; height: 35px;'><b>METER CHANGE OPERATIONS REPORT</b></th></tr>";
echo "<tr><td colspan='13'></td></tr>";

echo "<tr><td colspan='2'><b>Generated By:</b></td><td colspan='11'>{$generated_by}</td></tr>";
echo "<tr><td colspan='2'><b>Date Generated:</b></td><td colspan='11'>" . date('Y-m-d H:i:s') . "</td></tr>";
echo "<tr><td colspan='2'><b>Filter Status:</b></td><td colspan='11'>{$status_print}</td></tr>";
echo "<tr><td colspan='2'><b>Filter Phase:</b></td><td colspan='11'>{$phase_print}</td></tr>";
echo "<tr><td colspan='2'><b>Date Range:</b></td><td colspan='11'>{$date_print}</td></tr>";
echo "<tr><td colspan='2'><b>Search Keyword:</b></td><td colspan='11'>{$search_print}</td></tr>";
echo "<tr><td colspan='2'><b>Total Records:</b></td><td colspan='11'>{$total_count}</td></tr>";
echo "<tr><td colspan='13'></td></tr>";

// Table Headers
echo "<tr>";
echo "<th><b>ID</b></th>";
echo "<th><b>JOB NO</b></th>";
echo "<th><b>ACCOUNT NO</b></th>";
echo "<th><b>PHASE</b></th>";
echo "<th><b>OLD METER NO</b></th>";
echo "<th><b>OLD READING</b></th>";
echo "<th><b>STATUS</b></th>";
echo "<th><b>CREATED DATE</b></th>";
echo "<th><b>DONE BY</b></th>";
echo "<th><b>DONE DATE</b></th>";
echo "<th><b>NEW METER NO</b></th>";
echo "<th><b>NEW READING</b></th>";
echo "<th><b>OFFICER NOTE</b></th>";
echo "</tr>";

if ($total_count > 0) {
    while ($r = $res->fetch_assoc()) {
        $created_date = !empty($r['created_at']) ? date('Y-m-d H:i', strtotime($r['created_at'])) : '';
        $done_date = !empty($r['done_date']) ? $r['done_date'] : '';
        
        echo "<tr>";
        echo "<td>" . ($r['id'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['job_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['acc_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['phase_type'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['old_meter_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['old_reading'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['status'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($created_date) . "</td>";
        echo "<td>" . htmlspecialchars($r['done_by'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($done_date) . "</td>";
        echo "<td>" . htmlspecialchars($r['new_meter_no'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['new_reading'] ?? '') . "</td>";
        echo "<td>" . htmlspecialchars($r['officer_note'] ?? '') . "</td>";
        echo "</tr>";
    }
} else {
    echo "<tr><td colspan='13' style='text-align:center;'>No records found for the selected criteria.</td></tr>";
}

// Signature area
echo "<tr><td colspan='13'></td></tr>";
echo "<tr><td colspan='13'></td></tr>";
echo "<tr><td colspan='13'></td></tr>";

echo "<tr>";
echo "<td colspan='4' style='text-align:center; border: none;'>......................................................</td>";
echo "<td colspan='5' style='border: none;'></td>";
echo "<td colspan='4' style='text-align:center; border: none;'>......................................................</td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='4' style='text-align:center; border: none;'><b>Prepared By</b></td>";
echo "<td colspan='5' style='border: none;'></td>";
echo "<td colspan='4' style='text-align:center; border: none;'><b>Approved By (Electrical Superintendent)</b></td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='4' style='text-align:center; border: none;'>{$generated_by}</td>";
echo "<td colspan='5' style='border: none;'></td>";
echo "<td colspan='4' style='text-align:center; border: none;'></td>";
echo "</tr>";

echo "<tr>";
echo "<td colspan='4' style='text-align:center; border: none;'>Date: ........................</td>";
echo "<td colspan='5' style='border: none;'></td>";
echo "<td colspan='4' style='text-align:center; border: none;'>Date: ........................</td>";
echo "</tr>";

echo "</table>";
echo "</body></html>";
exit();
